#!/usr/bin/env python3
"""Pre-render uishim-rx3 button labels in the style of rbp's pre-drawn button labels (e.g. MY SETTINGS MENU on the
source screen): 25 px (18 px label height; first fitted with Helvetica, now Liberation Sans), +0.1 px letter spacing, measured against the on-screen label
(252 px wide for "MY SETTINGS MENU"). Writes rx3-rootfs/shims/label_font.h with cropped 8-bit alpha bitmaps.

Run anywhere with Pillow (font: tools/fonts/LiberationSans-Regular.ttf):
    .venv-serial/bin/python tools/gen_labels.py
"""
import os
from PIL import Image, ImageDraw, ImageFont

# Liberation Sans (SIL Open Font License, tools/fonts/): free, with Helvetica/Arial metrics. The labels were first
# fitted with Apple's Helvetica; set LABEL_FONT to use another font file.
FONT = os.environ.get('LABEL_FONT', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fonts', 'LiberationSans-Regular.ttf'))
SIZE, TRACK = 25, 0.1
LABELS = [('EJ_IDLE', 'EJECT USB1'), ('EJ_STOPPING', 'EJECTING USB1 ...'),
          ('EJ_SAFE', 'SAFE TO REMOVE USB1'), ('EJ_BUSY', 'USB1 BUSY - TRY AGAIN'),
          ('EJ2_IDLE', 'EJECT USB2'), ('EJ2_STOPPING', 'EJECTING USB2 ...'),
          ('EJ2_SAFE', 'SAFE TO REMOVE USB2'), ('EJ2_BUSY', 'USB2 BUSY - TRY AGAIN')]

# power-off messages, larger (shown in a box centred on the screen)
MSG_SIZE = 40
MESSAGES = [('PW_OFF', 'POWERING OFF ...'), ('PW_SAFE', 'SAFE TO UNPLUG')]

out = ['/* generated by tools/gen_labels.py — do not edit */',
       '/* %s %d px (18 px caps), +%.1f px tracking: matches rbp\'s pre-drawn button labels */' % (os.path.basename(FONT), SIZE, TRACK),
       'struct label_bitmap { int w, h, cap_top; const unsigned char *a; };']


def render(labels, size, arrname, track=None):
    track = TRACK if track is None else track
    font = ImageFont.truetype(FONT, size)
    ents = []
    for name, text in labels:
        im = Image.new('L', (1200, 120), 0)
        d = ImageDraw.Draw(im)
        x = 10.0
        for c in text:
            d.text((x, 10), c, font=font, fill=255)
            x += font.getlength(c) + track
        box = im.getbbox()
        im = im.crop(box)
        cap_top = font.getbbox('M')[1] + 10 - box[1]
        data = list(im.getdata())
        out.append('static const unsigned char lbl_%s[%d] = {' % (name.lower(), len(data)))
        for i in range(0, len(data), 24):
            out.append('    ' + ','.join(str(v) for v in data[i:i + 24]) + ',')
        out.append('};')
        ents.append('    { %d, %d, %d, lbl_%s },  /* %s */' % (im.width, im.height, cap_top, name.lower(), text))
    out.append('static const struct label_bitmap %s[%d] = {' % (arrname, len(labels)))
    out.extend(ents)
    out.append('};')
    return ents


# INFO screen: TAG TRACK (same style as EJECT USB1; removing is on the TAG LIST screen)
TAG_LABELS = [('TAG', 'TAG TRACK')]

entries = render(LABELS, SIZE, 'eject_labels')
entries += render(TAG_LABELS, SIZE, 'tag_labels')
entries += render(MESSAGES, MSG_SIZE, 'power_labels')
# SOURCE screen, in place of EJECT while knobshim's USB1 heal reports rbp stuck
entries += render([('STUCK', 'USB1 STUCK - HOLD TO RESTART'), ('RESTART', 'RESTARTING PLAYER ...'),
                  ('STUCK_HOLD', 'KEEP HOLDING ...')], SIZE, 'stuck_labels')
# Beat FX QUANTIZE button: matches the panel's small caps (CH SELECT): 13 px (10 px caps), -0.25 tracking,
# fitted to the on-screen CH SELECT (71 px wide)
entries += render([('FXQ', 'QUANTIZE')], 13, 'fxq_labels', -0.25)
# MASTER CUE indicator under the Beat FX panel (same small caps)
entries += render([('MCUE', 'MASTER CUE')], 13, 'mcue_labels', -0.25)
out.append('#define LABEL_CAP 18')
out.append('#define FXQ_CAP 10')
out.append('#define MSG_CAP %d' % (ImageFont.truetype(FONT, MSG_SIZE).getbbox('M')[3] - ImageFont.truetype(FONT, MSG_SIZE).getbbox('M')[1]))
dst = os.path.join(os.path.dirname(__file__), '..', 'rx3-rootfs', 'shims', 'label_font.h')
open(dst, 'w').write('\n'.join(out) + '\n')
print('wrote', os.path.normpath(dst), [(e.split('/*')[1].strip(' */')) for e in entries])
